### ISSUE TITLE
Feathers-sync breaks when trying to authenticate

### ISSUE THREAD

**Issue by Sieabah** [feathersjs/feathers-sync#62]
### Steps to reproduce

Run feathers-sync backed by redis.

`

    synk_1       | /srv/synk/node_modules/feathers-authentication/lib/socket/update-entity.js:4

    synk_1       |   var app = meta.app;

    synk_1       |                 ^

    synk_1       |

    synk_1       | TypeError: Cannot read property 'app' of undefined

    synk_1       |     at Object.updateEntity (/srv/synk/node_modules/feathers-authentication/lib/socket/update-entity.js:4:17)

    synk_1       |     at emitOne (events.js:101:20)

    synk_1       |     at Object.emit [as _emit] (events.js:188:7)

    synk_1       |     at RedisClient.<anonymous> (/srv/synk/node_modules/feathers-sync/src/redis.js:28:27)

    synk_1       |     at emitTwo (events.js:111:20)

    synk_1       |     at RedisClient.emit (events.js:191:7)

    synk_1       |     at return_pub_sub (/srv/synk/node_modules/redis/index.js:781:18)

    synk_1       |     at RedisClient.return_reply (/srv/synk/node_modules/redis/index.js:828:9)

    synk_1       |     at JavascriptRedisParser.returnReply (/srv/synk/node_modules/redis/index.js:192:18)

    synk_1       |     at JavascriptRedisParser.execute (/srv/synk/node_modules/redis/node_modules/redis-parser/lib/parser.js:574:12)

    synk_1       |     at Socket.<anonymous> (/srv/synk/node_modules/redis/index.js:274:27)

    synk_1       |     at emitOne (events.js:96:13)

    synk_1       |     at Socket.emit (events.js:188:7)

    synk_1       |     at readableAddChunk (_stream_readable.js:176:18)

    synk_1       |     at Socket.Readable.push (_stream_readable.js:134:10)

    synk_1       |     at TCP.onread (net.js:547:20)
`
### Expected behavior
Should sync between servers using a redis connector provided

### Actual behavior
meta is undefined

### System configuration

`
const sync = require('feathers-sync');

    app.configure(sync({
        db: `redis://${host}:${port}`,
      }));
`

**Module versions** (especially the part that's not working):
feathers: ^2.1.4
feathers-sync: ^0.1.3

**NodeJS version**:
v6 or v8 (both fail)

**Comment by Sieabah** [comment]
Looks like it happens 100% of the time when you try to log in an already authenticated user.
